### ISSUE TITLE
Moving into @rose-pine/palette

### ISSUE THREAD

**Issue by mvllow** [barelyhuman/rose-pine-css#2]
Appreciate you making this! I must've manually typed our palette as css variables half a dozen times.

I would love to get this into https://github.com/rose-pine/palette but am curious of your thoughts on the best way to do this as I am unsure how to maintain your commit history and such (to give you full credit for this addition).

**Comment by barelyhuman** [comment]
there's various ways 
1. Patch file 
2. Squashed commit reference

the easiest one is for me to just make the change in your repo as a fork and raise a PR, i'll get that done soon, 
Should've actually done that originally 😂 , I was too lazy to ask and hear and no so I just made this. 

I'll raise a PR soon
